### PR TITLE
Port changes ament java: update how to export jars

### PR DESCRIPTION
**Pull request by ivanpauno**
Starting to contribute back from https://github.com/osrf/ros2_java.
These are the first three commits in `osrf:galactic-devel` that differ from `main`.

I think we will also need to merge https://github.com/ros2-java/ament_java/pull/15 together with this.
Maybe we can first merge that PR without deleting the .sh and .bat templates, and then merge this one (to avoid breaking CI in the middle).

### CODE REVIEW

**Comment by jacobperron** [comment]
I don't recall if there was an issue leaving the old .sh and .bat templates, but if you have the bandwidth could you try and open a PR leaving them in?

**Comment by jacobperron** [comment]
Or, I suppose we could just merge ros2-java/ament_java#15, since we don't care too much about being backwards compatible.

**Comment by jacobperron** [comment]
@ivanpauno Can you add a commit to this PR that updates the repos file(s) to use the new `main` branch of `ament_java`?

**Comment by ivanpauno** [comment]
> @ivanpauno Can you add a commit to this PR that updates the repos file(s) to use the new `main` branch of `ament_java`?

Sounds good!
I'm first moving to https://github.com/jacobperron/ament_java/tree/reapply_10 to see if that makes CI pass.
If that works, we can merge https://github.com/ros2-java/ament_java/pull/15 to the new `ament_java` main branch and then merge this one (including the commit that switches to ament_java main branch).

**Comment by ivanpauno** [comment]
> If that works, we can merge ros2-java/ament_java#15 to the new ament_java main branch and then merge this one (including the commit that switches to ament_java main branch).

Okay that worked, using ament_java main branch now.
We can merge this one after https://github.com/ros2-java/ament_java/pull/15 gets merged.

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
