### PR TITLE
Port changes from osrf/galactic-devel

### PR DESCRIPTION
**Pull request by jacobperron**
Contains significant changes/additions related to Actions, QoS, ROS time, and graph APIs. This brings in all changes we've developed on our fork that are compatible with Galactic: https://github.com/osrf/ros2_java/tree/galactic-devel

For posterity, each commit references the pull request to the OSRF fork where review and any discussion occurred.

### CODE REVIEW

**Comment by jacobperron** [comment]
There is an unexpected test failure on linux CI:

```
 5: 1) testAdd(org.ros2.rcljava.client.ClientTest)
  5: java.lang.AssertionError: expected:<1> but was:<7>
  5: 	at org.junit.Assert.fail(Assert.java:88)
  5: 	at org.junit.Assert.failNotEquals(Assert.java:834)
  5: 	at org.junit.Assert.assertEquals(Assert.java:645)
  5: 	at org.junit.Assert.assertEquals(Assert.java:631)
  5: 	at org.ros2.rcljava.client.ClientTest.testAdd(ClientTest.java:131)
  5: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  5: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  5: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  5: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  5: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  5: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  5: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  5: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  5: 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  5: 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  5: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  5: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  5: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  5: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  5: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  5: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  5: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  5: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  5: 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  5: 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  5: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  5: 	at org.junit.runners.Suite.runChild(Suite.java:128)
  5: 	at org.junit.runners.Suite.runChild(Suite.java:27)
  5: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  5: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  5: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  5: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  5: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  5: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  5: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  5: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  5: 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
  5: 	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

There are also, not-so-unexpected, build issues on android (since we're not running CI on our fork). I'll resolve these before merging any commits contained in this PR.

**Comment by esteve** [comment]
@jacobperron first of all, thanks for the PR. But in all honesty, reviewing a 8K+ line diff is a lot of work, is there any chance this could be broken into separate features? Given that you and @ivanpauno both have write access to this repo, could you in the future do the work directly here? We did a sync months ago, and I thought that from then on, all development would be done upstream.

**Comment by jacobperron** [comment]
Technically, either Ivan or I have already reviewed the changes in this PR (though I understand if we want to break this into separate smaller PRs). We've done previous PRs (https://github.com/ros2-java/ros2_java/pull/199 and https://github.com/ros2-java/ros2_java/pull/206) to start porting changes over, but there are a number of outstanding changes to upstream. I collected all remaining changes from our fork that we tested with Galactic and put them in this PR. I am hoping after this, there will be one more PR that adds changes for Humble/Rolling and then we can archive our fork.

**Comment by jacobperron** [comment]
Thanks for opening up smaller PRs, @ivanpauno. I'll close this one in favor of those.

**Comment by bluecamel** [comment]
I don't see that there was a separate PR to port the action server from the osrf fork.  Is that still a WIP?

**Pull request closed without merging**
