### PR TITLE
change code order(methodId 'add' in for loop)

### PR DESCRIPTION
**Pull request by pluris**
'jmethodID jlist@(member.name)_add_mid' is not required in the for loop.
In my opinion, it should be declared outside for loop.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM.

I'm looking into the CI failure, which appears unrelated.

**Comment by jacobperron** [comment]
@pluris Can you try rebasing your changes on the latest version of the `dashing` branch? I'm hoping it will resolve the CI failure.

**Comment by pluris** [comment]
@jacobperron okay, I rebased it.

**Comment by jacobperron** [comment]
@pluris Thanks for the patch!

**Pull request merged**
